### ISSUE TITLE
Cannot read API key on cygwin

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-cli-deploy#5]
When trying to deploy from cygwin, the following exception is thrown:

```
Exception in thread "main" java.lang.RuntimeException: Could not get API key! Please install the toolbelt and login with `heroku login` or set the HEROKU_API_KEY environment variable.
        at com.heroku.sdk.deploy.Deployer.getEncodedApiKey(Deployer.java:211)
        at com.heroku.sdk.deploy.Deployer.mergeConfigVars(Deployer.java:106)
        at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:68)
        at com.heroku.sdk.deploy.App.deploy(App.java:57)
        at com.heroku.sdk.deploy.App.deploy(App.java:61)
        at com.heroku.sdk.deploy.WarApp.deploy(WarApp.java:30)
        at com.heroku.sdk.deploy.DeployWar.main(DeployWar.java:101)
```

**Comment by skygreen2001** [comment]
same problem,any help?
